[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = false

[tasks.setup]
script = '''
    echo # things required for `cargo make test`
    cargo install cargo-nextest

    echo # things required by `cargo make coverage`
    rustup component add llvm-tools-preview
    cargo install cargo-llvm-cov

    echo # things required by `cargo make audit`
    cargo install cargo-audit
'''

[tasks.lint]
command = "cargo"
args = [
    "clippy",
    "--tests",
    "--examples",
    "--all-targets",
    "--all-features",
    "--workspace",
]

[tasks.format]
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.test]
env = { RUN_MODE = "test", RUST_LOG = "info" }
command = "cargo"
args = ["nextest", "run", "--workspace", "${@}"]

[tasks.test-ci]
env = { RUN_MODE = "ci", RUST_LOG = "info" }
command = "cargo"
args = ["nextest", "run", "--workspace"]

[tasks.cov]
command = "cargo"
env = { RUN_MODE = "test" }
args = ["llvm-cov", "nextest", "${@}"]

[tasks.cov-ci]
command = "cargo"
env = { RUN_MODE = "ci" }
args = ["llvm-cov", "nextest", "--lcov", "--output-path", "lcov.info"]

[tasks.integration]
env = { RUN_MODE = "test", RUST_LOG = "info", RUST_BACKTRACE = 1 }
command = "cargo"
args = [
    "nextest",
    "run",
    "--features=integration",
    "--workspace",
    "--run-ignored=ignored-only",
    "${@}",
]

[tasks.integration-ci]
env = { RUN_MODE = "ci", RUST_LOG = "info" }
command = "cargo"
args = [
    "nextest",
    "run",
    "--features=integration",
    "--workspace",
    "--run-ignored=ignored-only",
]

[tasks.docs]
command = "cargo"
args = [
    "doc",
    "--no-deps",
    "--all-features",
    "--document-private-items",
    "--workspace",
    "--examples",
]

[tasks.audit]
command = "cargo"
args = ["audit"]

[tasks.timings]
script = '''
    cargo clean
    cargo build --release --quiet --timings
    xdg-open /target/cargo-timings/cargo-timing.html
'''

[tasks.dev]
env = { RUST_LOG = "info" }
command = "cargo"
args = ["run", "--bin", "sylled"]
watch = true
